# Numpy basics

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a

array([1, 2, 3])

In [7]:
b = np.array([[1,2,3], [4,5,6]])

In [8]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
a.shape

(3,)

## This is markdown


#### Datatype

In [11]:
b.dtype

dtype('int32')

In [12]:
a.dtype

dtype('int32')

#### Dimension

In [13]:
a.ndim

1

In [15]:
b.ndim

2

#### Type

In [16]:
print(type(a))

<class 'numpy.ndarray'>


#### Array having range

In [17]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Performance measurement

In [18]:
c = range(10000)
%timeit (i**3 for i in c )

281 ns ± 43.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
print(type(c))

<class 'range'>


In [19]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

16.5 µs ± 211 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
l1 = range(10000)
l2 = [ i ** 2 for i in range(10000)]
%timeit list(map(lambda x,y: x*y, l1,l2))

948 µs ± 10.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Conversion of list into array

In [22]:
a1 = np.array(l1)
b1 = np.array(l2)

In [23]:
print(type(a1))

<class 'numpy.ndarray'>


In [24]:
%timeit a1 * b1

8.24 µs ± 73.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [25]:
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Creating numpy array

In [26]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
a1[1]

1

In [35]:
a1[3]

3

In [37]:
x = np.full((3,3),2)

In [38]:
y = np.ones((3,1))

In [39]:
x*y

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [40]:
x

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [41]:
y

array([[1.],
       [1.],
       [1.]])

In [42]:
np.full((3,3),2.2, dtype=int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [43]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### Stacks n copies of x on top of each other

In [45]:
np.tile(x,(2,1))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
np.random.rand()

0.511712909210333

In [47]:
50 + np.random.rand() **2

50.10829505731515

In [50]:
np.random.random([2,1])

array([[0.95093215],
       [0.2867945 ]])

#### 100 values between 1-50

In [51]:
v = np.linspace(1,50,100)

In [52]:
v

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [53]:
v.itemsize

8

In [59]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [60]:
np.arange(6).reshape(2,3,1)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

Automatically adjusts to dimension

In [62]:
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [63]:
a = np.arange(10)

In [64]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a[2:5]

array([2, 3, 4])

In [66]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
a[(a>2) & (a<5)]

array([3, 4])

#### Subset of array

In [70]:
a = np.arange(10)

In [71]:
b = a

In [72]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
b[1] = 12

In [74]:
b

array([ 0, 12,  2,  3,  4,  5,  6,  7,  8,  9])

In [75]:
np.shares_memory(a,b)

True

In [76]:
a = np.arange(10)

In [77]:
b = a.copy()

In [78]:
b[1] = 50

In [79]:
b

array([ 0, 50,  2,  3,  4,  5,  6,  7,  8,  9])

In [80]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.shares_memory(a,b)

False

In [82]:
a = np.array([[1,2,3],[3,4,5]])

In [83]:
b = np.array([[6,7,8],[9,1,3]])

In [84]:
a == b

array([[False, False, False],
       [False, False, False]])

Vertical stack

In [85]:
np.vstack((a,b))

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [9, 1, 3]])

Horizantal stack

In [86]:
np.hstack((a,b))

array([[1, 2, 3, 6, 7, 8],
       [3, 4, 5, 9, 1, 3]])

Transpose

In [87]:
a.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [88]:
np.stack((a,b) , axis=1)

array([[[1, 2, 3],
        [6, 7, 8]],

       [[3, 4, 5],
        [9, 1, 3]]])

In [89]:
np.stack((a,b) , axis=0)

array([[[1, 2, 3],
        [3, 4, 5]],

       [[6, 7, 8],
        [9, 1, 3]]])

In [90]:
a.b

AttributeError: 'numpy.ndarray' object has no attribute 'b'

In [91]:
b

array([[6, 7, 8],
       [9, 1, 3]])

In [92]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [93]:
np.dot(a,a)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [94]:
np.dot(a,a.T)

array([[14, 26],
       [26, 50]])

In [95]:
a.sum()

18

In [96]:
a.sum(axis=1)

array([ 6, 12])

In [97]:
a.argmax()

5

In [98]:
a[: ,np.newaxis].shape

(2, 1, 3)

In [99]:
np.sort(a)

array([[1, 2, 3],
       [3, 4, 5]])

In [100]:
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)